### ISSUE TITLE
How ... Interlace handling should be turned on

### ISSUE THREAD

**Issue by aoreinoso** [Nakilon/dhash-vips#11]
```none
/usr/local/lib/ruby/gems/3.0.0/gems/ruby-vips-2.0.17/lib/vips/operation.rb:190:in `build': vipspng: Interlace handling should be turned on when using png_read_image (Vips::Error)
vipspng: Interlace handling should be turned on when using png_read_image
extract_area: bad extract area
	from /usr/local/lib/ruby/gems/3.0.0/gems/ruby-vips-2.0.17/lib/vips/operation.rb:402:in `call'
	from /usr/local/lib/ruby/gems/3.0.0/gems/ruby-vips-2.0.17/lib/vips/image.rb:211:in `method_missing'
	from /usr/local/lib/ruby/gems/3.0.0/gems/dhash-vips-0.1.1.3/lib/dhash-vips.rb:24:in `calculate'
```

My code:

```ruby
Dir["/home/xxx/tmp/**/*"].each do |fichero|
      begin
	      puts fichero
	      hash1 = DHashVips::DHash.calculate fichero
	      hash2 = DHashVips::DHash.calculate fichero
	      #puts "#{hash1} #{hash2} #{fichero}"
      #rescue
      #	puts "ERROR------------: #{fichero}"
      end
end
```

How...  Interlace handling should be turned on ?

thank you in advance

**Comment by Nakilon** [comment]
This looks like something about libvips.
The only things I've found are https://github.com/libvips/libvips/issues/1620 and https://github.com/libvips/libvips/pull/1296

@jcupitt I'm sorry for pinging you again in my project but maybe you know what causes it and maybe you have some details like "upgrade something to version something".

P.S.: if the fix needs some newest ruby-vips gem version it will not be compatible with currently published dhash-vips.gemspec yet so it might need custom dhash-vips.gemspec included in your project edited like this https://github.com/Nakilon/dhash-vips/pull/7
I didn't yet test the gem and its build on newer versions since the time I got stuck with that native extensions don't compile on Alpine.

**Comment by jcupitt** [comment]
Hi @Nakilon, I think this is just an old libvips version. 

libpng changed their API to force you to enable interlace handling. Recent libvips have this extra code, older ones do not.

@aoreinoso what do you see for:

```
john@banana ~/try $ irb
irb(main):001:0> require "vips"
=> true
irb(main):002:0> Vips::version_string
=> "8.12.0-Sun Jul 18 13:46:28 UTC 2021"
```

8.11 is current stable.

**Comment by Nakilon** [comment]
@aoreinoso  have you resolved your issue?
